
name: Build and Run Flask API

on:
  push:
    branches:
      - 'main'
    paths:
      - 'flask-api/**'
      - '.github/workflows/flask-api.yml'
  pull_request:
    branches:
      - 'main'
    paths:
      - 'flask-api/**'
      - '.github/workflows/flask-api.yml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Log in to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: flask-api
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/user/app:latest
            ghcr.io/user/app:1.0.0
